// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KK0uHcSzJmyAdiRiAlk58JhSvU_Df6o',
    appId: '1:441905533532:web:5f0fd5712f09fa7dbb0c99',
    messagingSenderId: '441905533532',
    projectId: 'pawrtal-rabbit-hole',
    authDomain: 'pawrtal-rabbit-hole.firebaseapp.com',
    storageBucket: 'pawrtal-rabbit-hole.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZaITzSgmoSL59CIcRJhk2Ow9cgI74QU',
    appId: '1:441905533532:android:3aa253135ac965a3bb0c99',
    messagingSenderId: '441905533532',
    projectId: 'pawrtal-rabbit-hole',
    storageBucket: 'pawrtal-rabbit-hole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hg8bhs6w-LWvNqutLdUSE2RykA4WAPY',
    appId: '1:441905533532:ios:e165245964324748bb0c99',
    messagingSenderId: '441905533532',
    projectId: 'pawrtal-rabbit-hole',
    storageBucket: 'pawrtal-rabbit-hole.appspot.com',
    androidClientId: '441905533532-cpmrfprc71mmmc9dj4kqor2lrqvg14k9.apps.googleusercontent.com',
    iosClientId: '441905533532-iej1qbjq67l5qbbp5h417jl6j0gfebu7.apps.googleusercontent.com',
    iosBundleId: 'com.bnuuy.pawrtal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-hg8bhs6w-LWvNqutLdUSE2RykA4WAPY',
    appId: '1:441905533532:ios:e165245964324748bb0c99',
    messagingSenderId: '441905533532',
    projectId: 'pawrtal-rabbit-hole',
    storageBucket: 'pawrtal-rabbit-hole.appspot.com',
    androidClientId: '441905533532-cpmrfprc71mmmc9dj4kqor2lrqvg14k9.apps.googleusercontent.com',
    iosClientId: '441905533532-iej1qbjq67l5qbbp5h417jl6j0gfebu7.apps.googleusercontent.com',
    iosBundleId: 'com.bnuuy.pawrtal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8KK0uHcSzJmyAdiRiAlk58JhSvU_Df6o',
    appId: '1:441905533532:web:b2732510309f97c0bb0c99',
    messagingSenderId: '441905533532',
    projectId: 'pawrtal-rabbit-hole',
    authDomain: 'pawrtal-rabbit-hole.firebaseapp.com',
    storageBucket: 'pawrtal-rabbit-hole.appspot.com',
  );

}